### ISSUE TITLE
1.1.0 release on npm is lagging behind others

### ISSUE THREAD

**Issue by berekuk** [drmonty/chosen#1]
I'm using `drmonty-chosen` via `react-chosen` and npm. Can you upload the latest version to npm, please?

**Comment by mrohnstock** [comment]
crap, I've published 1.4.0 before 1.3.0... npm will list 1.3.0 as latest version. I can't [unpublish](https://docs.npmjs.com/cli/unpublish) 1.4.0 and publish the version again, to make it the latest version.

We have to deal with it (or force `drmonty-chosen@1.4.0` to fetch latest version).

Sorry...

**Comment by mrohnstock** [comment]
Alright, 1.4.1 is now the latest.
