### ISSUE TITLE
Pull from upstream

### ISSUE THREAD

**Issue by hawkeyetwolf** [drmonty/chosen#2]
Thanks for making this shim repo! Would you mind cutting a new release for the latest from Harvest?

**Comment by hawkeyetwolf** [comment]
Actually, ideally, this would live in the http://github.com/components org. How about adding @robloach and me as maintainers and that way we can help keep it updated?

**Comment by RobLoach** [comment]
https://github.com/components/chosen

I'll add both of you 👍

**Comment by mrohnstock** [comment]
Thanks @RobLoach  for picking up this shim :). I were not using this plugin for my project anymore, so it was stuck for a while.

I think, I gonna remove this repo, as it won't receive updates anymore.
